# Site
name: "WTF - What's the F**!"
title: "WTF - What's the F**!"
description: |
  After Monday and Tuesday, even the calendar says 'WTF'.<br>
  WTF - disappointingly for some, is an acronym for 'What's The Fun?'<br>
  Join me, <a href="about#aboutme">Balajee Thachakkadu Mohan</a>; as we explore the fun side of many things under the sun.<br>
  Let's have fun as we discard the sugarcoats!<br>
  Come let's unjargon.
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: 
google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/


# Authors
authors:
  bala:
    name: Balajee Thachakkadu Mohan
    display_name: Balajee™
    avatar: 'assets/images/bala.png'
#    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: balajee.tm@gmail.com
    web: https://blog.balajeetm.com
    linkedin: https://www.linkedin.com/in/balajeetm/
    twitter: https://twitter.com/balajeetm
    posts: true
    description: |
      <b class="text-success">Director Technology | Publicis Sapient</b><br>
      A self proclaimed geek, creative genius, visionary, brave risk-taker, healthy sport, avocational writer and an astute liar. ;)<br>
      A passionate Software Techy, who is inclined towards problem solving.
  dheeraj:
    name: Dheeraj Kysetti
    display_name: Dheeraj
    linkedin: https://www.linkedin.com/in/dheeraj-kysetti-845261a/
    post: false
    description: |
      <b class="text-success">Chief Architect | Tesco Technology</b><br>
      Builds fault tolerant Distributed Applications that scale on-demand. Has in-depth knowledge on Distributed technologies toolkit which enable him to solve wide class of distributed problem statements at internet scale.
  mahesh:
    name: Mahesh Kumar R
    posts: false
    display_name: Mahesh Kumar
    avatar: 'assets/images/mahesh.jpg'
    description: |
      <b class="text-success">Chief Operating Officer | Expressive Life</b><br>
      Entrepreneur, Innovator & Creative designer.<br>
      Driving initiatives & business strategy to solve customer problems.
  chandan:
    name: Chandan Kumar Singha
    display_name: Chandan Singha
    avatar: 'assets/images/chandan.jpg'
    web: https://chandan.xyz/
    linkedin: https://www.linkedin.com/in/chandansingha/
    post: false
    description: |
      <b class="text-success">Chief Technology Officer | Litifer Technologies</b><br>
      Wears multiple hats from writing code, managing infrastructure, working on analytics, strategizing content, and evangelizing products. His interests lies in Distributed Systems, Kubernetes, cloud, security, algorithms, data structures.
  prajwal:
    name: Prajwal Gurumurthy
    display_name: Prajwal Gurumurthy
    web: https://prajwalgurumurthy.github.io/
    linkedin: https://www.linkedin.com/in/prajwal-gurumurthy/
    post: false
    description: |
      <b class="text-success">Chief Architect | Tesco Technology</b><br>
      Believes simplicity is the purest form of knowledge. Responsible for 3DR[ Design, Development, Deployment and Run] of omni basket, transactional Enterprise Customer Order APIs at retail scale for TESCO.



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - year
  layouts:
    category: archive_category
    year: archive_year
  permalinks:
    category: '/category/:name/'
    year: '/archives/year/:year/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
